import Provider from "@/shared/providers/provider"
import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import "./globals.css"

const nunito = Nunito({
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Free chess analyzer",
	description: "Generated by create next app",
}

export default function AppLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="ru" className={`${nunito.className} h-full antialiased `}>
			<Provider>
				<body className="min-h-full flex flex-col background text-primary">{children}</body>
			</Provider>
		</html>
	)
}
